version: '3'
services:
  etcdv3:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    working_dir: '/app'
    volumes:
      - '.:/app'
    environment:
      HISTFILE: '/app/.bash-history'